=== madgeek-arc/resource-catalogue/resource-catalogue-model/src/main/resources/schemas/json/Vocabulary-schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Map(String,String)" : {
      "type" : "object",
      "additionalProperties" : false
    }
  },
  "type" : "object",
  "properties" : {
    "description" : {
      "type" : "string"
    },
    "extras" : {
      "$ref" : "#/$defs/Map(String,String)"
    },
    "id" : {
      "type" : "string"
    },
    "name" : {
      "type" : "string"
    },
    "parentId" : {
      "type" : "string"
    },
    "type" : {
      "type" : "string"
    }
  },
  "additionalProperties" : false
}

=== madgeek-arc/resource-catalogue/resource-catalogue-service/src/main/resources/vocabularies/REGION.json
[
  {
    "id": "AH",
    "name": "Schengen Area",
    "description": "All Schengen Area countries.",
    "parentId": "geographic_location",
    "type": "Region",
    "extras": {}
  },
  {
    "id": "EO",
    "name": "Europe",
    "description": "All European Countries.",
    "parentId": "geographic_location",
    "type": "Region",
    "extras": {}
  },
  {
    "id": "EU",
    "name": "European Union",
    "description": "All Countries of the European Union.",
    "parentId": "geographic_location",
    "type": "Region",
    "extras": {}
  },
  {
    "id": "EZ",
    "name": "Euro Zone",
    "description": "All Countries of the Eurozone.",
    "parentId": "geographic_location",
    "type": "Region",
    "extras": {}
  },
  {
    "id": "WW",
    "name": "Worldwide",
    "description": "All Countries.",
    "parentId": "geographic_location",
    "type": "Region",
    "extras": {}
  }
]
